import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import "~/globals.css";
import { TooltipProvider } from "~/components/ui/tooltip";
import { Layout } from "../components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body className="h-screen w-screen flex items-center justify-center">
        <NextIntlClientProvider messages={messages}>
          <TooltipProvider>
            <Layout>{children}</Layout>
          </TooltipProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
