create table "public"."channel_memberships" (
    "id" bigint generated by default as identity not null,
    "account_id" bigint not null,
    "channel_id" bigint not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."channel_memberships" enable row level security;

create table "public"."channels" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "description" text,
    "created_by" bigint not null,
    "team_id" bigint not null,
    "client_id" bigint,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone
);


alter table "public"."channels" enable row level security;

create table "public"."client_portal_assignments" (
    "id" bigint generated by default as identity not null,
    "client_portal_id" bigint not null,
    "account_id" bigint not null,
    "updated_at" timestamp with time zone,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."client_portal_assignments" enable row level security;

create table "public"."client_portals" (
    "id" bigint generated by default as identity not null,
    "name" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "team_id" bigint not null
);


alter table "public"."client_portals" enable row level security;

create table "public"."clients" (
    "id" bigint generated by default as identity not null,
    "name" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "team_id" bigint not null,
    "client_portal_id" bigint
);


alter table "public"."clients" enable row level security;

create table "public"."messages" (
    "id" bigint generated by default as identity not null,
    "content" text not null,
    "account_id" bigint not null,
    "origin_id" bigint not null,
    "origin_type" text not null default 'channel'::text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone
);


alter table "public"."messages" enable row level security;

create table "public"."task_assignments" (
    "id" bigint generated by default as identity not null,
    "task_id" bigint not null,
    "account_id" bigint,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone
);


alter table "public"."task_assignments" enable row level security;

create table "public"."tasks" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "description" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "completed_at" timestamp with time zone,
    "completed_by" bigint,
    "worked_hours" smallint,
    "epic_id" bigint,
    "project_id" bigint,
    "client_id" bigint,
    "team_id" bigint
);


alter table "public"."tasks" enable row level security;

CREATE UNIQUE INDEX channel_memberships_pkey ON public.channel_memberships USING btree (id);

CREATE UNIQUE INDEX channels_pkey ON public.channels USING btree (id);

CREATE UNIQUE INDEX client_portal_assignments_pkey ON public.client_portal_assignments USING btree (id);

CREATE UNIQUE INDEX client_portals_pkey ON public.client_portals USING btree (id);

CREATE UNIQUE INDEX clients_pkey ON public.clients USING btree (id);

CREATE UNIQUE INDEX messages_pkey ON public.messages USING btree (id);

CREATE UNIQUE INDEX task_assignments_pkey ON public.task_assignments USING btree (id);

CREATE UNIQUE INDEX tasks_pkey ON public.tasks USING btree (id);

alter table "public"."channel_memberships" add constraint "channel_memberships_pkey" PRIMARY KEY using index "channel_memberships_pkey";

alter table "public"."channels" add constraint "channels_pkey" PRIMARY KEY using index "channels_pkey";

alter table "public"."client_portal_assignments" add constraint "client_portal_assignments_pkey" PRIMARY KEY using index "client_portal_assignments_pkey";

alter table "public"."client_portals" add constraint "client_portals_pkey" PRIMARY KEY using index "client_portals_pkey";

alter table "public"."clients" add constraint "clients_pkey" PRIMARY KEY using index "clients_pkey";

alter table "public"."messages" add constraint "messages_pkey" PRIMARY KEY using index "messages_pkey";

alter table "public"."task_assignments" add constraint "task_assignments_pkey" PRIMARY KEY using index "task_assignments_pkey";

alter table "public"."tasks" add constraint "tasks_pkey" PRIMARY KEY using index "tasks_pkey";

alter table "public"."channel_memberships" add constraint "channel_memberships_account_id_fkey" FOREIGN KEY (account_id) REFERENCES accounts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."channel_memberships" validate constraint "channel_memberships_account_id_fkey";

alter table "public"."channel_memberships" add constraint "channel_memberships_channel_id_fkey" FOREIGN KEY (channel_id) REFERENCES channels(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."channel_memberships" validate constraint "channel_memberships_channel_id_fkey";

alter table "public"."channels" add constraint "channels_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."channels" validate constraint "channels_client_id_fkey";

alter table "public"."channels" add constraint "channels_created_by_fkey" FOREIGN KEY (created_by) REFERENCES accounts(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."channels" validate constraint "channels_created_by_fkey";

alter table "public"."channels" add constraint "channels_team_id_fkey" FOREIGN KEY (team_id) REFERENCES teams(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."channels" validate constraint "channels_team_id_fkey";

alter table "public"."client_portal_assignments" add constraint "client_portal_assignments_account_id_fkey" FOREIGN KEY (account_id) REFERENCES accounts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."client_portal_assignments" validate constraint "client_portal_assignments_account_id_fkey";

alter table "public"."client_portal_assignments" add constraint "client_portal_assignments_client_portal_id_fkey" FOREIGN KEY (client_portal_id) REFERENCES client_portals(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."client_portal_assignments" validate constraint "client_portal_assignments_client_portal_id_fkey";

alter table "public"."client_portals" add constraint "client_portals_team_id_fkey" FOREIGN KEY (team_id) REFERENCES teams(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."client_portals" validate constraint "client_portals_team_id_fkey";

alter table "public"."clients" add constraint "clients_team_id_fkey" FOREIGN KEY (team_id) REFERENCES teams(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."clients" validate constraint "clients_team_id_fkey";

alter table "public"."messages" add constraint "messages_account_id_fkey" FOREIGN KEY (account_id) REFERENCES accounts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."messages" validate constraint "messages_account_id_fkey";

alter table "public"."task_assignments" add constraint "task_assignments_account_id_fkey" FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE SET NULL not valid;

alter table "public"."task_assignments" validate constraint "task_assignments_account_id_fkey";

alter table "public"."task_assignments" add constraint "task_assignments_task_id_fkey" FOREIGN KEY (task_id) REFERENCES tasks(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."task_assignments" validate constraint "task_assignments_task_id_fkey";

grant delete on table "public"."channel_memberships" to "anon";

grant insert on table "public"."channel_memberships" to "anon";

grant references on table "public"."channel_memberships" to "anon";

grant select on table "public"."channel_memberships" to "anon";

grant trigger on table "public"."channel_memberships" to "anon";

grant truncate on table "public"."channel_memberships" to "anon";

grant update on table "public"."channel_memberships" to "anon";

grant delete on table "public"."channel_memberships" to "authenticated";

grant insert on table "public"."channel_memberships" to "authenticated";

grant references on table "public"."channel_memberships" to "authenticated";

grant select on table "public"."channel_memberships" to "authenticated";

grant trigger on table "public"."channel_memberships" to "authenticated";

grant truncate on table "public"."channel_memberships" to "authenticated";

grant update on table "public"."channel_memberships" to "authenticated";

grant delete on table "public"."channel_memberships" to "service_role";

grant insert on table "public"."channel_memberships" to "service_role";

grant references on table "public"."channel_memberships" to "service_role";

grant select on table "public"."channel_memberships" to "service_role";

grant trigger on table "public"."channel_memberships" to "service_role";

grant truncate on table "public"."channel_memberships" to "service_role";

grant update on table "public"."channel_memberships" to "service_role";

grant delete on table "public"."channels" to "anon";

grant insert on table "public"."channels" to "anon";

grant references on table "public"."channels" to "anon";

grant select on table "public"."channels" to "anon";

grant trigger on table "public"."channels" to "anon";

grant truncate on table "public"."channels" to "anon";

grant update on table "public"."channels" to "anon";

grant delete on table "public"."channels" to "authenticated";

grant insert on table "public"."channels" to "authenticated";

grant references on table "public"."channels" to "authenticated";

grant select on table "public"."channels" to "authenticated";

grant trigger on table "public"."channels" to "authenticated";

grant truncate on table "public"."channels" to "authenticated";

grant update on table "public"."channels" to "authenticated";

grant delete on table "public"."channels" to "service_role";

grant insert on table "public"."channels" to "service_role";

grant references on table "public"."channels" to "service_role";

grant select on table "public"."channels" to "service_role";

grant trigger on table "public"."channels" to "service_role";

grant truncate on table "public"."channels" to "service_role";

grant update on table "public"."channels" to "service_role";

grant delete on table "public"."client_portal_assignments" to "anon";

grant insert on table "public"."client_portal_assignments" to "anon";

grant references on table "public"."client_portal_assignments" to "anon";

grant select on table "public"."client_portal_assignments" to "anon";

grant trigger on table "public"."client_portal_assignments" to "anon";

grant truncate on table "public"."client_portal_assignments" to "anon";

grant update on table "public"."client_portal_assignments" to "anon";

grant delete on table "public"."client_portal_assignments" to "authenticated";

grant insert on table "public"."client_portal_assignments" to "authenticated";

grant references on table "public"."client_portal_assignments" to "authenticated";

grant select on table "public"."client_portal_assignments" to "authenticated";

grant trigger on table "public"."client_portal_assignments" to "authenticated";

grant truncate on table "public"."client_portal_assignments" to "authenticated";

grant update on table "public"."client_portal_assignments" to "authenticated";

grant delete on table "public"."client_portal_assignments" to "service_role";

grant insert on table "public"."client_portal_assignments" to "service_role";

grant references on table "public"."client_portal_assignments" to "service_role";

grant select on table "public"."client_portal_assignments" to "service_role";

grant trigger on table "public"."client_portal_assignments" to "service_role";

grant truncate on table "public"."client_portal_assignments" to "service_role";

grant update on table "public"."client_portal_assignments" to "service_role";

grant delete on table "public"."client_portals" to "anon";

grant insert on table "public"."client_portals" to "anon";

grant references on table "public"."client_portals" to "anon";

grant select on table "public"."client_portals" to "anon";

grant trigger on table "public"."client_portals" to "anon";

grant truncate on table "public"."client_portals" to "anon";

grant update on table "public"."client_portals" to "anon";

grant delete on table "public"."client_portals" to "authenticated";

grant insert on table "public"."client_portals" to "authenticated";

grant references on table "public"."client_portals" to "authenticated";

grant select on table "public"."client_portals" to "authenticated";

grant trigger on table "public"."client_portals" to "authenticated";

grant truncate on table "public"."client_portals" to "authenticated";

grant update on table "public"."client_portals" to "authenticated";

grant delete on table "public"."client_portals" to "service_role";

grant insert on table "public"."client_portals" to "service_role";

grant references on table "public"."client_portals" to "service_role";

grant select on table "public"."client_portals" to "service_role";

grant trigger on table "public"."client_portals" to "service_role";

grant truncate on table "public"."client_portals" to "service_role";

grant update on table "public"."client_portals" to "service_role";

grant delete on table "public"."clients" to "anon";

grant insert on table "public"."clients" to "anon";

grant references on table "public"."clients" to "anon";

grant select on table "public"."clients" to "anon";

grant trigger on table "public"."clients" to "anon";

grant truncate on table "public"."clients" to "anon";

grant update on table "public"."clients" to "anon";

grant delete on table "public"."clients" to "authenticated";

grant insert on table "public"."clients" to "authenticated";

grant references on table "public"."clients" to "authenticated";

grant select on table "public"."clients" to "authenticated";

grant trigger on table "public"."clients" to "authenticated";

grant truncate on table "public"."clients" to "authenticated";

grant update on table "public"."clients" to "authenticated";

grant delete on table "public"."clients" to "service_role";

grant insert on table "public"."clients" to "service_role";

grant references on table "public"."clients" to "service_role";

grant select on table "public"."clients" to "service_role";

grant trigger on table "public"."clients" to "service_role";

grant truncate on table "public"."clients" to "service_role";

grant update on table "public"."clients" to "service_role";

grant delete on table "public"."messages" to "anon";

grant insert on table "public"."messages" to "anon";

grant references on table "public"."messages" to "anon";

grant select on table "public"."messages" to "anon";

grant trigger on table "public"."messages" to "anon";

grant truncate on table "public"."messages" to "anon";

grant update on table "public"."messages" to "anon";

grant delete on table "public"."messages" to "authenticated";

grant insert on table "public"."messages" to "authenticated";

grant references on table "public"."messages" to "authenticated";

grant select on table "public"."messages" to "authenticated";

grant trigger on table "public"."messages" to "authenticated";

grant truncate on table "public"."messages" to "authenticated";

grant update on table "public"."messages" to "authenticated";

grant delete on table "public"."messages" to "service_role";

grant insert on table "public"."messages" to "service_role";

grant references on table "public"."messages" to "service_role";

grant select on table "public"."messages" to "service_role";

grant trigger on table "public"."messages" to "service_role";

grant truncate on table "public"."messages" to "service_role";

grant update on table "public"."messages" to "service_role";

grant delete on table "public"."task_assignments" to "anon";

grant insert on table "public"."task_assignments" to "anon";

grant references on table "public"."task_assignments" to "anon";

grant select on table "public"."task_assignments" to "anon";

grant trigger on table "public"."task_assignments" to "anon";

grant truncate on table "public"."task_assignments" to "anon";

grant update on table "public"."task_assignments" to "anon";

grant delete on table "public"."task_assignments" to "authenticated";

grant insert on table "public"."task_assignments" to "authenticated";

grant references on table "public"."task_assignments" to "authenticated";

grant select on table "public"."task_assignments" to "authenticated";

grant trigger on table "public"."task_assignments" to "authenticated";

grant truncate on table "public"."task_assignments" to "authenticated";

grant update on table "public"."task_assignments" to "authenticated";

grant delete on table "public"."task_assignments" to "service_role";

grant insert on table "public"."task_assignments" to "service_role";

grant references on table "public"."task_assignments" to "service_role";

grant select on table "public"."task_assignments" to "service_role";

grant trigger on table "public"."task_assignments" to "service_role";

grant truncate on table "public"."task_assignments" to "service_role";

grant update on table "public"."task_assignments" to "service_role";

grant delete on table "public"."tasks" to "anon";

grant insert on table "public"."tasks" to "anon";

grant references on table "public"."tasks" to "anon";

grant select on table "public"."tasks" to "anon";

grant trigger on table "public"."tasks" to "anon";

grant truncate on table "public"."tasks" to "anon";

grant update on table "public"."tasks" to "anon";

grant delete on table "public"."tasks" to "authenticated";

grant insert on table "public"."tasks" to "authenticated";

grant references on table "public"."tasks" to "authenticated";

grant select on table "public"."tasks" to "authenticated";

grant trigger on table "public"."tasks" to "authenticated";

grant truncate on table "public"."tasks" to "authenticated";

grant update on table "public"."tasks" to "authenticated";

grant delete on table "public"."tasks" to "service_role";

grant insert on table "public"."tasks" to "service_role";

grant references on table "public"."tasks" to "service_role";

grant select on table "public"."tasks" to "service_role";

grant trigger on table "public"."tasks" to "service_role";

grant truncate on table "public"."tasks" to "service_role";

grant update on table "public"."tasks" to "service_role";


